version: "3"
services:
  app:
    container_name: flask_app
    build: ./Backend
    ports:
      - "5000:5000"
    # volumes:
    #   - ./app:/app
    depends_on:
      - db

  db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: SoulmateDB
      MYSQL_ROOT_PASSWORD: Soulmate_db22
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci